Apt editor
OpenSAGE/OpenSAGE pull request #510
Opened 2020-11-19 05:00 UTC by BSG-75

- Allow Viewing (not really) & Editing of Apt files
Tested (by tested I mean it usually doesn't crash) on: BFME apt files, [RA3 UI Source Pack](https://www.moddb.com/games/cc-red-alert-3/downloads/ra3-mod-ui-source-pack)
#### Things that are (a bit) working:
- Opening Apt files (and resolving their imports, currently not well implemented, but kinda works)
- Creating `Shape` / `Geometry` (geometry handled in a text editor)
- Creating / Editing `PlaceObject` in a `Playable`'s `Frame`
- Exporting Apt files
#### Main things that are still missing:
- Correct geometry transformation
- All Apt Characters expect `Sprite` and `Shape`
- Everything ActionScript related (actually now AptEditor uses a hack to prevent OpenSage from executing ActionScript)
- Creation of new frames, creation of multi-frame interpolation animation (like what Adobe Flash does)
- Edit geometries in a interactive editor instead of text editor
- Edit `ImageMap` / import more custom textures

2020-12-28 09:17 UTC, tgjones approved these changes
This looks amazing, thank you! I didn’t go through it line by line but in broad brush strokes the code looks good to me.

2020-12-28 12:09 UTC, Tarcontar commented
Sadly this causes some issues with the bfme ui.
![image](https://user-images.githubusercontent.com/10086882/103213418-e4fb2980-490d-11eb-9ba8-390d488f77d9.png)

2020-12-28 12:24 UTC, feliwir requested changes

2020-12-28 12:24 UTC, feliwir commented on src/OpenSage.Game/Gui/Apt/AptRenderingContext.cs
> +                text.LocalizedContent,
This is wrong

2020-12-28 12:24 UTC, feliwir commented on src/OpenSage.Game/Gui/Apt/RenderItem.cs
> +            t.LocalizedContent = t.Content
No

2020-12-28 12:26 UTC, feliwir commented
@BSG-75 your changes to the Text Content do cause some issues for BFME, see the screenshot from @Tarcontar

2021-01-06 17:49 UTC, Tarcontar commented
lookin good now in bfme and bfme2! :)

2021-01-06 18:22 UTC, merged