Fix MapCache load error on Linux
OpenSAGE/OpenSAGE pull request #557
Opened 2021-05-01 03:41 UTC by wrightjjw

Fixes #543. `GetByName()` expects a Windows filepath, so it changes `mapPath` to one before calling it.

2021-05-01 06:45 UTC, andreinonea commented
This check happens at run-time. I noticed in `OpenSage.Game/OpenSage.Game.csproj`, there are already platform checks, albeit for another reason.

```
<PropertyGroup>                                                               
  <GlslangValidatorPath>win-x64\glslangValidator.exe</GlslangValidatorPath>   
  <GlslangValidatorPath Condition="$([MSBuild]::IsOsPlatform('osx'))">osx-x64\glslangValidator</GlslangValidatorPath>
  <GlslangValidatorPath Condition="$([MSBuild]::IsOsPlatform('linux'))">linux-x64\glslangValidator</GlslangValidatorPath>
</PropertyGroup>
```                                                          
Thus, I propose a simple addition to the `.csproj` file that creates defines for each platform.

```
<PropertyGroup Condition="'$(GlslangValidatorPath)'=='win-x64\glslangValidator.exe'">
  <DefineConstants>_WINDOWS_</DefineConstants>                                
</PropertyGroup>                                                              
 
<PropertyGroup Condition="'$(GlslangValidatorPath)'!='win-x64\glslangValidator.exe'">
  <DefineConstants>_UNIX_</DefineConstants>                                   
</PropertyGroup>                                                              
 
<PropertyGroup Condition="'$(GlslangValidatorPath)'=='osx-x64\glslangValidator'">
  <DefineConstants>_MACOSX_</DefineConstants>                                 
</PropertyGroup>                                                              
 
<PropertyGroup Condition="'$(GlslangValidatorPath)'=='linux-x64\glslangValidator'">
  <DefineConstants>_LINUX_</DefineConstants>                                  
</PropertyGroup>
```
Then, we could simply write

```
if (mapPath != null)                                                
{                                                                   
#if _UNIX_                                                          
    mapPath = mapPath.Replace("/", "\\");                           
#endif                                                              
    var mapCache = game.AssetStore.MapCaches.GetByName(mapPath.ToLower());
    ...
    ...
```
in `OpenSage.Game/Scene3D.cs`, which is even more readable and also has the advantage of happening at compile-time.

Please note that I **have NOT tested** this on my machine because of another bug which prevents me from starting the Launcher, so I might be wrong. It all goes under the assumption that `$([MSBuild]::IsOsPlatform())` does work indeed in this scenario.

2021-05-01 12:18 UTC, wrightjjw commented
That's definitely a better idea. I'll test it out when I get a chance.

2021-05-01 15:34 UTC, wrightjjw commented
Made changes based on @andreinonea's suggestion. Similar result to original solution.

2021-05-02 16:32 UTC, dginovker commented
Ty for fixing up Linux :heart_eyes:. It wasn't even starting for me a few months ago <3

2021-05-21 19:55 UTC, tgjones requested changes
Hello! I'm sorry for not reviewing this PR before. I _think_ it would be better to instead change this line:

https://github.com/OpenSAGE/OpenSAGE/blob/c0c8940c7c181745c27bd1acb64ccad4253e147d/src/OpenSage.Game/Content/MapCache.cs#L12

to this:

``` csharp
(x, name) => x.SetNameAndInstanceId("MapCache", FileSystem.NormalizeFilePath(IniParser.ToAsciiString(name))),
```

In general, all paths used at runtime are supposed to use the correct path separators for the current platform. But that is one place where we missed it, because the `MapCache` keys themselves are paths.

2021-05-22 15:04 UTC, wrightjjw commented
Thanks for looking into it. Yeah, that fix is a lot simpler and better. I'm quite busy for a couple days but I will look into this sometime in the next week.

2021-06-06 18:26 UTC, closed without merging

2021-06-06 18:34 UTC, wrightjjw commented
Opening a clean branch to fix this.

2022-01-27 01:32 UTC, cbordeman commented
You don't need a Windows define for this, the .Net APIs and nearly all Win32 APIs can use forward slash in paths without issue.  They have since XP at least.